### ISSUE TITLE
Construct ATA for formulas other than until and dual until

### ISSUE THREAD

**Issue by morxa** [morxa/mtlsyn#62]
We currently only support until and dual until as outermost connector. Extend this for conjunctions, disjunctions, atomic propositions, and negations of atomic propositions.

**Comment by modass** [comment]
Some comments/guides for the implementation:
- each until induces two new locations, one to realize the strict semantics and contains the respective _phi^i_, i.e., which reflects that _some_ symbol needs to be read. For any symbol of the alphabet, a transition leads to a location with a formula which reflects the satisfaction of the until itself.
- all other operators/connectives can be reflected via the recursive init-function.
- if the outermost connective is neither until nor dual-until, we might need another location (to be checked)

**Comment by morxa** [comment]
Fixed in #64.
